### ISSUE TITLE
slow simulation

### ISSUE THREAD

**Issue by adwardlee** [hzwer/NIPS2017-LearningToRunACE#8]
Hi @hzwer ,

Thanks for sharing your good work. Do you take any steps to accelerate the simulation process since it takes so much time? When I change the accuracy mentioned by ctmakro, the network is hard to converge. Thanks.

**Comment by hzwer** [comment]
I remember another team did it https://medium.com/mlreview/our-nips-2017-learning-to-run-approach-b80a295d3bb5 <https://medium.com/mlreview/our-nips-2017-learning-to-run-approach-b80a295d3bb5>
Because I was new to machine learning at that time, I didn't try too much.
I remembered that this method could’t accelerate so much in my mac OS system

**Comment by adwardlee** [comment]
Thanks for your quick reply. It can be 3-4 times faster in linux at least. It is weird that network cannot learn at all at lower accuracy when "self.manager.setIntegratorAccuracy(1e-2)"  according to https://github.com/stanfordnmbl/osim-rl/issues/78.
